# Generated by Django 3.2.6 on 2021-08-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listagemeventos',
            fields=[
                ('idListagemEventos', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idListagemEventos')),
                ('tipo_evento', models.IntegerField()),
                ('descricao_tipo_evento', models.CharField(max_length=255)),
                ('base', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
