# Generated by Django 3.2.6 on 2021-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historicodeeventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.IntegerField(blank=True, null=True)),
                ('descricao_tipo_evento', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('veic_oras_codigo', models.IntegerField(blank=True, null=True)),
                ('numero_terminal', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnologia', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('data_bordo', models.DateTimeField(blank=True, null=True)),
                ('posicao', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('codigo_viagem', models.IntegerField(blank=True, null=True)),
                ('viag_numero_manifesto', models.IntegerField(blank=True, null=True)),
                ('esis_usuario_adicionou', models.CharField(blank=True, max_length=255, null=True)),
                ('pess_nome_adicionou', models.CharField(blank=True, max_length=255, null=True)),
                ('pess_oras_codigo_adicionou', models.IntegerField(blank=True, null=True)),
                ('pess_oras_codigo_leitura', models.IntegerField(blank=True, null=True)),
                ('usua_login_leitura', models.CharField(blank=True, max_length=255, null=True)),
                ('pess_nome_leitura', models.CharField(blank=True, max_length=255, null=True)),
                ('pess_oras_codigo_supervisao', models.IntegerField(blank=True, null=True)),
                ('usua_login_supervisao', models.CharField(blank=True, max_length=255, null=True)),
                ('pess_nome_supervisao', models.CharField(blank=True, max_length=255, null=True)),
                ('esis_data_leitura', models.DateTimeField(blank=True, null=True)),
                ('esis_desc_tratamento', models.CharField(blank=True, max_length=255, null=True)),
                ('motorista', models.CharField(blank=True, max_length=255, null=True)),
                ('verificado', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitaalertasinal', models.CharField(blank=True, max_length=1, null=True)),
                ('informativomotorista', models.CharField(blank=True, max_length=1, null=True)),
                ('informativogrupo', models.CharField(blank=True, max_length=1, null=True)),
                ('data_hora_integrada', models.DateTimeField(blank=True, null=True)),
                ('data_hora_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
