# Generated by Django 3.2.6 on 2021-08-05 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('historicoeventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicodeeventos',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='historicodeeventos',
            name='solicitaalertasinal',
        ),
        migrations.AddField(
            model_name='historicodeeventos',
            name='acionamentoPR',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='historicodeeventos',
            name='acionamentoPamcary',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='historicodeeventos',
            name='alertasinal',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='historicodeeventos',
            name='email',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='data_hora_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='data_hora_integrada',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='informativogrupo',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='informativomotorista',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='verificado',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
