# Generated by Django 3.2.6 on 2021-08-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicoeventos', '0002_auto_20210805_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicodeeventos',
            name='acionamentoPR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='acionamentoPamcary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='alertasinal',
            field=models.IntegerField(default=0),
        ),
    ]
