# Generated by Django 3.2.6 on 2021-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicoeventos', '0003_auto_20210806_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicodeeventos',
            name='esis_desc_tratamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicodeeventos',
            name='posicao',
            field=models.TextField(),
        ),
    ]
