# Generated by Django 3.2.6 on 2021-08-06 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertasinal',
            fields=[
                ('idAlertaSinal', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idListagemEventos')),
                ('placa', models.CharField(max_length=255)),
                ('referencia', models.CharField(max_length=500)),
                ('sessao', models.CharField(max_length=500)),
                ('data_hora_acionamento', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cancelado', models.IntegerField()),
                ('id_evento', models.IntegerField()),
            ],
        ),
    ]
