# Generated by Django 3.2.6 on 2021-08-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertasinal', '0002_alter_alertasinal_idalertasinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertasinal',
            name='referencia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alertasinal',
            name='sessao',
            field=models.TextField(),
        ),
    ]
