# Generated by Django 3.2.6 on 2021-08-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210804_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idGrupo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
