# Generated by Django 3.2.6 on 2021-08-07 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridade',
            fields=[
                ('idAutoridade', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idAutoridade')),
                ('nomeAutoridade', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('sigla', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('emails', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('data_hora_cadastro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
